### PR TITLE
add support for play-pause, next track & previous track buttons

### PR DESCRIPTION
**Pull request by phated**
I added global shortcuts tied to the media keys for Play/Pause and Next/Previous Track buttons.  I also did work for volume up/down/mute but didn't include it in this PR because I'm not sure it makes sense.  Do you think it should be supported or not (In VLC, they don't tie the volume control to those buttons)?

### CODE REVIEW

**Comment by feross** [comment]
Volume keys are usually left to the OS to handle.

**Comment by phated** [comment]
@feross yeah, thought so.  I really like when you can control chromecast with volume buttons though (usually on Android).

**Comment by feross** [comment]
Oh, that's actually a neat idea. But I think users would find it very
surprising on OS X.

**Comment by phated** [comment]
@feross yeah, I'm currently thinking about a "preferences" menu option and maybe it could contain an option for that.

**Comment by feross** [comment]
That's amusing -- we're working on the same thing in WebTorrent Desktop right now.

**Comment by freeall** [comment]
I don't know any programs (at least in osx) that override volume up/down behaviour. But the rest are neat.

And a jumbo :+1: for controlling volume in Chromecast. I very often have that need. Often you then need "another" remote to control the volume and that's kinda stupid.

**Pull request merged**
